# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackAtlApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



  # Pods for HackAtlApp

  pod 'Firebase/Core'

  target 'HackAtlAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HackAtlApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HackAtlApp-tvOS

  target 'HackAtlApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
